### ISSUE TITLE
sparklines are out of order

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-irma#57]
They should be sorted south to north (based on latitude of the site)

**Comment by wdwatkins** [comment]
The number of sites needs to be thinned out a good bit too.  It's a bit of a jumbled mess right now.

**Comment by dblodgett-usgs** [comment]
I'm on this but don't have enough permissions to assign myself.

**Comment by dblodgett-usgs** [comment]
So... turns out that, while we are passing sites to data retrieval in sorted order, what we get back isn't sorted anymore. So we can either sort the dataretrieval response [here](https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/scripts/process/process.storm_sites.R#L54) or pull data out of it in sorted order [here](https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/scripts/process/process.discharge_sparks.R#L20). 

I'll implement one or the other, but will need some dplyr help if the former is the solution.

**Comment by jordansread** [comment]
hmmm - seems like something we should suggest as an improvement in dataRet, but yeah, we probably shouldn't count on getting sorted back anyhow. 

the former seems easier

**Comment by dblodgett-usgs** [comment]
Sorting would maybe best be done when drawing the sparklines though? Which is the second solution.

**Comment by jordansread** [comment]
or you could sort the sparkline data.frame that comes out. That is probably easier. You could sneak a sites call from dataRet to get the lat, and sort on that after a left_join.

**Comment by dblodgett-usgs** [comment]
👍 I think that's going to be easiest. Staring at dplyr black magic thinking -- I hate this.

**Comment by dblodgett-usgs** [comment]
OK, so I sorted them. Still out of order. I'm wondering if the flows aren't scaled right so they are plotting all over the place?

**Comment by dblodgett-usgs** [comment]
I've tracked this all through. I get to the clip step in building the base map and everything looks fine. What I realized is that the sites were not in the right place but it seems like the spark lines ARE ok with the changes I've made.

**Comment by dblodgett-usgs** [comment]
Fixed in #43
